#!/bin/bash

if [ "$TRAVIS_PULL_REQUEST" != "false" ]
then
  ./Pods/SwiftLint/swiftlint --reporter json > swiftlint-report.json || false
  linterbot $TRAVIS_REPO_SLUG $TRAVIS_PULL_REQUEST < swiftlint-report.json
fi